export const FEATURE_FLAG_ENUM = {
  PILATES_TOOLKIT: 'PILATES_TOOLKIT',
  MEDICAL_COMPLIANCE: 'MEDICAL_COMPLIANCE',
  AGENCY_RETAINER: 'AGENCY_RETAINER',
  MARKETING_AUTOMATION: 'MARKETING_AUTOMATION',
  EMBED_WIDGETS: 'EMBED_WIDGETS',
} as const;

export type FeatureFlagKey = (typeof FEATURE_FLAG_ENUM)[keyof typeof FEATURE_FLAG_ENUM];

export const FEATURE_FLAG_VALUES = Object.values(FEATURE_FLAG_ENUM);


