export const PERMISSIONS = {
  MANAGE_BUSINESS: 'manage_business',
  MANAGE_STAFF: 'manage_staff',
  MANAGE_SERVICES: 'manage_services',
  MANAGE_APPOINTMENTS: 'manage_appointments',
  MANAGE_CUSTOMERS: 'manage_customers',
  MANAGE_BOOKING_PAGES: 'manage_booking_pages',
  VIEW_FINANCIALS: 'view_financials',
  MANAGE_FINANCIALS: 'manage_financials',
  VIEW_AUDIT_LOGS: 'view_audit_logs',
  MANAGE_AVAILABILITY: 'manage_availability',
  MANAGE_TENANTS: 'manage_tenants',
  IMPERSONATE_TENANT: 'impersonate_tenant',
} as const;

export type Permission = (typeof PERMISSIONS)[keyof typeof PERMISSIONS];

export const ROLE_PERMISSION_MAP: Record<string, Permission[]> = {
  owner: [
    PERMISSIONS.MANAGE_BUSINESS,
    PERMISSIONS.MANAGE_STAFF,
    PERMISSIONS.MANAGE_SERVICES,
    PERMISSIONS.MANAGE_APPOINTMENTS,
    PERMISSIONS.MANAGE_CUSTOMERS,
    PERMISSIONS.MANAGE_BOOKING_PAGES,
    PERMISSIONS.VIEW_FINANCIALS,
    PERMISSIONS.MANAGE_FINANCIALS,
    PERMISSIONS.VIEW_AUDIT_LOGS,
    PERMISSIONS.MANAGE_AVAILABILITY,
  ],
  staff: [PERMISSIONS.MANAGE_AVAILABILITY, PERMISSIONS.MANAGE_APPOINTMENTS],
  admin: [
    PERMISSIONS.MANAGE_BUSINESS,
    PERMISSIONS.MANAGE_STAFF,
    PERMISSIONS.MANAGE_SERVICES,
    PERMISSIONS.VIEW_FINANCIALS,
    PERMISSIONS.VIEW_AUDIT_LOGS,
  ],
  superadmin: Object.values(PERMISSIONS),
  impersonation: [
    PERMISSIONS.MANAGE_BUSINESS,
    PERMISSIONS.MANAGE_APPOINTMENTS,
    PERMISSIONS.MANAGE_SERVICES,
    PERMISSIONS.MANAGE_STAFF,
    PERMISSIONS.MANAGE_CUSTOMERS,
    PERMISSIONS.MANAGE_BOOKING_PAGES,
    PERMISSIONS.MANAGE_AVAILABILITY,
  ],
};

